# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setStyleSheet("background-color: rgb(173, 203, 181);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_game = QtWidgets.QPushButton(self.centralwidget)
        self.btn_game.setGeometry(QtCore.QRect(125, 130, 150, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.btn_game.setFont(font)
        self.btn_game.setStyleSheet("background-color: rgb(124, 195, 152);")
        self.btn_game.setObjectName("btn_game")
        self.btn_watch_youtube = QtWidgets.QPushButton(self.centralwidget)
        self.btn_watch_youtube.setGeometry(QtCore.QRect(125, 170, 150, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_watch_youtube.setFont(font)
        self.btn_watch_youtube.setStyleSheet("background-color: rgb(124, 195, 152);")
        self.btn_watch_youtube.setObjectName("btn_watch_youtube")
        self.lbl_greeting = QtWidgets.QLabel(self.centralwidget)
        self.lbl_greeting.setGeometry(QtCore.QRect(0, 80, 400, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lbl_greeting.setFont(font)
        self.lbl_greeting.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_greeting.setObjectName("lbl_greeting")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Таймер 2.0"))
        self.btn_game.setText(_translate("MainWindow", "Играть"))
        self.btn_watch_youtube.setText(_translate("MainWindow", "Смотреть YouTube"))
        self.lbl_greeting.setText(_translate("MainWindow", "Привет, Дружище!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
